####################################### VOLUMES #########################################

volumes:
  mariadb:
    name: mariadb
    driver: local
    driver_opts:
      device: /home/fde-carv/data/mariadb
      o : bind
      type : none
  wordpress:
    name: wordpress
    driver: local
    driver_opts:
      device: /home/fde-carv/data/wordpress
      o : bind
      type : none

####################################### NETWORKS ########################################

networks:
  inception:
    name: inception
    driver: bridge

####################################### SERVICES ########################################

services:
  mariadb:
    container_name: mariadb
    image: mariadb
    build: ./requirements/mariadb
    volumes:
      - mariadb:/var/lib/mysql
      - /home/fbubuntu/fred/FRED/42_PORTO/12-INCEPTION/fred_v1/Inception/srcs:/app/srcs
    ports:
      - 3306:3306
    env_file :
      - .env
    networks :
      - inception
    restart: always

  nginx:
    container_name: nginx
    image: nginx
    build: ./requirements/nginx
    ports:
      - 443:443
    depends_on:
      - wordpress
    volumes:
      - wordpress:/var/www/wordpress
    networks:
      - inception
    restart: always

  wordpress:
    container_name: wordpress
    image: wordpress
    build: ./requirements/wordpress
    ports:
      - 9000:9000
    depends_on:
      - mariadb
    volumes:
      - wordpress:/var/www/wordpress
    env_file :
      - .env
    networks:
      - inception
    restart: always

######################################### BONUS #########################################

  # redis:
  #   container_name: redis
  #   build: ./requirements/bonus/redis/.
  #   image: redis
  #   volumes:
  #    - wordpress:/var/www/html
  #   depends_on:
  #     - wordpress
  #   networks:
  #     - inception
  #   restart: always

  # ftp:
  #   container_name: ftp
  #   build: ./requirements/bonus/ftp/.
  #   image: ftp
  #   depends_on:
  #     - wordpress
  #   volumes:
  #     - wordpress:/home/fde-carv/ftp/files
  #   env_file:
  #     - .env
  #   ports:
  #     - "21:21"
  #     - "20:20"
  #     - "40000-40005:40000-40005"
  #   networks:
  #     - inception
  #   restart: always

  # adminer:
  #   container_name: adminer
  #   build: ./requirements/bonus/adminer/.
  #   image: adminer
  #   depends_on:
  #     - mariadb
  #   ports:
  #     - "8080:80"
  #   dns:
  #     - 8.8.8.8
  #     - 8.8.4.4
  #   networks:
  #     - inception
  #   restart: always

  # website:
  #   container_name: website
  #   build: ./requirements/bonus/website/.
  #   image: website
  #   ports:
  #     - "3000:3000"
  #   networks:
  #     - inception
  #   restart: always

  # prometheus:
  #   container_name: prometheus
  #   build: ./requirements/bonus/prometheus/
  #   ports:
  #     - "9090:9090"
  #   volumes:
  #     - ./requirements/bonus/prometheus/conf/prometheus.yml:/etc/prometheus/prometheus.yml
  #   networks:
  #     - inception
  #   restart: always